--
-- PostgreSQL database dump
--

\restrict 2z5d5x24fXACI4QPYB7YNbH0fGRO7focjLt2RrhcjMPwYJcbBsfe75aIduRvnFa

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: ai_vendor; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.ai_vendor AS ENUM (
    'Anthropic',
    'OpenAI',
    'Google'
);


--
-- Name: employee_group; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.employee_group AS ENUM (
    'CUT',
    'DEVELOPER'
);


--
-- Name: task_effort; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_effort AS ENUM (
    'LOW (<1 HR)',
    'MEDIUM (1HR-3HR)',
    'HIGH (3HR-8HR)',
    'VERY HIGH (8HR-24HR)',
    'EXTREME (>24HR)'
);


--
-- Name: task_priority; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_priority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'CRITICAL'
);


--
-- Name: task_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_status AS ENUM (
    'OPEN',
    'IN PROGRESS',
    'RESOLVED'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_model_prompts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_model_prompts (
    ai_model_prompt_id bigint NOT NULL,
    ai_model_id bigint NOT NULL,
    ai_prompt_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    max_tokens bigint NOT NULL,
    default_prompt boolean DEFAULT false NOT NULL,
    update_existing boolean DEFAULT false NOT NULL
);


--
-- Name: ai_model_prompts_ai_model_prompt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_model_prompts ALTER COLUMN ai_model_prompt_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_model_prompts_ai_model_prompt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_models (
    ai_model_id bigint NOT NULL,
    ai_vendor public.ai_vendor NOT NULL,
    display_handle text NOT NULL,
    family text NOT NULL,
    family_version text NOT NULL,
    api_handle text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    input_price_per_mtok numeric(10,4) NOT NULL,
    output_price_per_mtok numeric(10,4) NOT NULL
);


--
-- Name: ai_models_ai_model_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_models ALTER COLUMN ai_model_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_models_ai_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_prompt_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_prompt_types (
    ai_prompt_type_id bigint NOT NULL,
    handle text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    description text
);


--
-- Name: ai_prompt_types_ai_prompt_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_prompt_types ALTER COLUMN ai_prompt_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_prompt_types_ai_prompt_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_prompts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_prompts (
    ai_prompt_id bigint NOT NULL,
    prompt text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    handle text NOT NULL,
    ai_prompt_type_id bigint NOT NULL
);


--
-- Name: ai_prompts_ai_prompt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_prompts ALTER COLUMN ai_prompt_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_prompts_ai_prompt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    country_id bigint NOT NULL,
    handle text NOT NULL,
    code_alpha2 character(2) NOT NULL,
    code_alpha3 character(3) NOT NULL,
    code_numeric character(3) NOT NULL,
    ship_to boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    collect_tax boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: countries_country_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.countries ALTER COLUMN country_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    employee_id bigint NOT NULL,
    name text NOT NULL,
    hawthorne_admin_passcode character(4),
    deleted boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    v2_attrs jsonb,
    deleted_at timestamp with time zone,
    login_name text NOT NULL,
    hawthorne_admin_site_passcode text NOT NULL,
    hr_role boolean DEFAULT false NOT NULL,
    admin_role boolean DEFAULT false NOT NULL,
    dev_ops_role boolean DEFAULT false NOT NULL,
    marketing_role boolean DEFAULT false NOT NULL,
    owner_role boolean DEFAULT false NOT NULL,
    customer_service_role boolean DEFAULT false NOT NULL,
    cut_group boolean DEFAULT false,
    developer_group boolean DEFAULT false,
    digital_printing_role boolean DEFAULT false NOT NULL
);


--
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flagged_http_referers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flagged_http_referers (
    flagged_http_referer_id bigint NOT NULL,
    http_referer text NOT NULL,
    reason text,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: flagged_http_referers_flagged_http_referer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.flagged_http_referers ALTER COLUMN flagged_http_referer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flagged_http_referers_flagged_http_referer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flagged_http_user_agents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flagged_http_user_agents (
    flagged_http_user_agent_id bigint NOT NULL,
    http_user_agent text NOT NULL,
    reason text,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    url text
);


--
-- Name: flagged_http_user_agents_flagged_http_user_agent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.flagged_http_user_agents ALTER COLUMN flagged_http_user_agent_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flagged_http_user_agents_flagged_http_user_agent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flagged_ips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flagged_ips (
    flagged_ip_id bigint NOT NULL,
    ip text NOT NULL,
    reason text,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: flagged_ips_flagged_ip_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.flagged_ips ALTER COLUMN flagged_ip_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flagged_ips_flagged_ip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: image_presets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_presets (
    image_preset_id bigint NOT NULL,
    handle text NOT NULL,
    widths integer[] NOT NULL,
    sizes text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: image_presets_image_preset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.image_presets ALTER COLUMN image_preset_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_presets_image_preset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: image_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_types (
    image_type_id bigint NOT NULL,
    handle text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    image_preset_id bigint NOT NULL,
    slug text
);


--
-- Name: image_types_image_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.image_types ALTER COLUMN image_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_types_image_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invalid_email_domains; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invalid_email_domains (
    invalid_email_domain_id bigint NOT NULL,
    handle text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    v2_attrs jsonb
);


--
-- Name: invalid_email_domains_invalid_email_domain_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invalid_email_domains ALTER COLUMN invalid_email_domain_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invalid_email_domains_invalid_email_domain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    note_id bigint NOT NULL,
    handle text NOT NULL,
    role text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: notes_note_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notes ALTER COLUMN note_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: page_block_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_block_types (
    page_block_type_id bigint NOT NULL,
    handle text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    content_attrs text[] NOT NULL,
    required_content_attrs text[] NOT NULL
);


--
-- Name: page_block_types_page_block_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.page_block_types ALTER COLUMN page_block_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.page_block_types_page_block_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: page_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.page_types (
    page_type_id bigint NOT NULL,
    handle text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: page_types_page_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.page_types ALTER COLUMN page_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.page_types_page_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_categories (
    task_category_id bigint NOT NULL,
    handle text NOT NULL,
    parent_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: task_categories_task_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_categories ALTER COLUMN task_category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_categories_task_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_comments (
    task_comment_id bigint NOT NULL,
    task_id bigint NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    employee_id bigint NOT NULL
);


--
-- Name: task_comments_task_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_comments ALTER COLUMN task_comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_comments_task_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_schedules (
    task_schedule_id bigint NOT NULL,
    task_category_id bigint NOT NULL,
    subject text NOT NULL,
    description text,
    priority public.task_priority NOT NULL,
    assigned_employee_id bigint,
    assigned_employee_group public.employee_group,
    frequency interval NOT NULL,
    anchor_at timestamp with time zone NOT NULL,
    next_run_at timestamp with time zone NOT NULL,
    last_run_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    effort public.task_effort NOT NULL
);


--
-- Name: task_schedules_task_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_schedules ALTER COLUMN task_schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_schedules_task_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    task_id bigint NOT NULL,
    task_category_id bigint NOT NULL,
    subject text NOT NULL,
    description text,
    status public.task_status,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    assigned_employee_id bigint,
    assigned_employee_group public.employee_group,
    priority public.task_priority NOT NULL,
    task_schedule_id bigint,
    effort public.task_effort CONSTRAINT tasks_task_effort_not_null NOT NULL,
    site_id bigint,
    release_nbr text
);


--
-- Name: tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tasks ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: us_states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.us_states (
    us_state_id bigint NOT NULL,
    handle text NOT NULL,
    code_alpha2 character(2) NOT NULL,
    ship_to boolean DEFAULT true NOT NULL,
    collect_tax boolean DEFAULT false NOT NULL,
    contiguous boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: us_states_us_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.us_states ALTER COLUMN us_state_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.us_states_us_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_model_prompts ai_model_prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_prompts
    ADD CONSTRAINT ai_model_prompts_pkey PRIMARY KEY (ai_model_prompt_id);


--
-- Name: ai_model_prompts ai_model_prompts_uk_ai_model_id_ai_prompt_id_max_tokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_prompts
    ADD CONSTRAINT ai_model_prompts_uk_ai_model_id_ai_prompt_id_max_tokens UNIQUE (ai_model_id, ai_prompt_id, max_tokens);


--
-- Name: ai_models ai_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_pkey PRIMARY KEY (ai_model_id);


--
-- Name: ai_models ai_models_uk_ai_vendor_family_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_uk_ai_vendor_family_version UNIQUE (ai_vendor, family, family_version);


--
-- Name: ai_models ai_models_uk_api_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_uk_api_handle UNIQUE (api_handle);


--
-- Name: ai_models ai_models_uk_display_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_uk_display_handle UNIQUE (display_handle);


--
-- Name: ai_prompt_types ai_prompt_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_prompt_types
    ADD CONSTRAINT ai_prompt_types_pkey PRIMARY KEY (ai_prompt_type_id);


--
-- Name: ai_prompt_types ai_prompt_types_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_prompt_types
    ADD CONSTRAINT ai_prompt_types_uk_handle UNIQUE (handle);


--
-- Name: ai_prompts ai_prompts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_prompts
    ADD CONSTRAINT ai_prompts_pkey PRIMARY KEY (ai_prompt_id);


--
-- Name: ai_prompts ai_prompts_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_prompts
    ADD CONSTRAINT ai_prompts_uk_handle UNIQUE (handle);


--
-- Name: countries countries_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pk PRIMARY KEY (country_id);


--
-- Name: countries countries_uk_code_alpha2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_uk_code_alpha2 UNIQUE (code_alpha2);


--
-- Name: countries countries_uk_code_alpha3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_uk_code_alpha3 UNIQUE (code_alpha3);


--
-- Name: countries countries_uk_code_numeric; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_uk_code_numeric UNIQUE (code_numeric);


--
-- Name: countries countries_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_uk_handle UNIQUE (handle);


--
-- Name: employees employees_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pk PRIMARY KEY (employee_id);


--
-- Name: employees employees_uk_login_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_uk_login_name UNIQUE (login_name);


--
-- Name: employees employees_uk_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_uk_name UNIQUE (name);


--
-- Name: flagged_http_referers flagged_http_referers_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flagged_http_referers
    ADD CONSTRAINT flagged_http_referers_pk PRIMARY KEY (flagged_http_referer_id);


--
-- Name: flagged_http_referers flagged_http_referers_uk_http_referer; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flagged_http_referers
    ADD CONSTRAINT flagged_http_referers_uk_http_referer UNIQUE (http_referer);


--
-- Name: flagged_http_user_agents flagged_http_user_agents_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flagged_http_user_agents
    ADD CONSTRAINT flagged_http_user_agents_pk PRIMARY KEY (flagged_http_user_agent_id);


--
-- Name: flagged_http_user_agents flagged_http_user_agents_uk_http_user_agent; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flagged_http_user_agents
    ADD CONSTRAINT flagged_http_user_agents_uk_http_user_agent UNIQUE (http_user_agent);


--
-- Name: flagged_ips flagged_ips_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flagged_ips
    ADD CONSTRAINT flagged_ips_pk PRIMARY KEY (flagged_ip_id);


--
-- Name: flagged_ips flagged_ips_uk_ip; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flagged_ips
    ADD CONSTRAINT flagged_ips_uk_ip UNIQUE (ip);


--
-- Name: image_presets image_presets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_presets
    ADD CONSTRAINT image_presets_pkey PRIMARY KEY (image_preset_id);


--
-- Name: image_presets image_presets_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_presets
    ADD CONSTRAINT image_presets_uk_handle UNIQUE (handle);


--
-- Name: image_types image_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_types
    ADD CONSTRAINT image_types_pkey PRIMARY KEY (image_type_id);


--
-- Name: image_types image_types_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_types
    ADD CONSTRAINT image_types_uk_handle UNIQUE (handle);


--
-- Name: invalid_email_domains invalid_email_domains_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invalid_email_domains
    ADD CONSTRAINT invalid_email_domains_pk PRIMARY KEY (invalid_email_domain_id);


--
-- Name: invalid_email_domains invalid_email_domains_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invalid_email_domains
    ADD CONSTRAINT invalid_email_domains_uk_handle UNIQUE (handle);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (note_id);


--
-- Name: notes notes_uk_handle_role; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_uk_handle_role UNIQUE (handle, role);


--
-- Name: page_block_types page_block_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_block_types
    ADD CONSTRAINT page_block_types_pkey PRIMARY KEY (page_block_type_id);


--
-- Name: page_block_types page_block_types_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_block_types
    ADD CONSTRAINT page_block_types_uk_handle UNIQUE (handle);


--
-- Name: page_types page_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_types
    ADD CONSTRAINT page_types_pkey PRIMARY KEY (page_type_id);


--
-- Name: page_types page_types_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.page_types
    ADD CONSTRAINT page_types_uk_handle UNIQUE (handle);


--
-- Name: task_categories task_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_categories
    ADD CONSTRAINT task_categories_pkey PRIMARY KEY (task_category_id);


--
-- Name: task_categories task_categories_uk_parent_id_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_categories
    ADD CONSTRAINT task_categories_uk_parent_id_handle UNIQUE (parent_id, handle);


--
-- Name: task_comments task_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT task_comments_pkey PRIMARY KEY (task_comment_id);


--
-- Name: task_schedules task_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_schedules
    ADD CONSTRAINT task_schedules_pkey PRIMARY KEY (task_schedule_id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (task_id);


--
-- Name: us_states us_states_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.us_states
    ADD CONSTRAINT us_states_pk PRIMARY KEY (us_state_id);


--
-- Name: us_states us_states_uk_code_alpha2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.us_states
    ADD CONSTRAINT us_states_uk_code_alpha2 UNIQUE (code_alpha2);


--
-- Name: us_states us_states_uk_handle; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.us_states
    ADD CONSTRAINT us_states_uk_handle UNIQUE (handle);


--
-- Name: tasks_task_schedule_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tasks_task_schedule_id_idx ON public.tasks USING btree (task_schedule_id);


--
-- Name: ai_model_prompts ai_model_prompts_ai_models_ai_model_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_prompts
    ADD CONSTRAINT ai_model_prompts_ai_models_ai_model_id_fk FOREIGN KEY (ai_model_id) REFERENCES public.ai_models(ai_model_id);


--
-- Name: ai_model_prompts ai_model_prompts_ai_prompts_ai_prompt_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_prompts
    ADD CONSTRAINT ai_model_prompts_ai_prompts_ai_prompt_id_fk FOREIGN KEY (ai_prompt_id) REFERENCES public.ai_prompts(ai_prompt_id);


--
-- Name: ai_prompts ai_prompts_ai_prompt_types_ai_prompt_type_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_prompts
    ADD CONSTRAINT ai_prompts_ai_prompt_types_ai_prompt_type_id_fk FOREIGN KEY (ai_prompt_type_id) REFERENCES public.ai_prompt_types(ai_prompt_type_id);


--
-- Name: image_types image_types_image_presets_image_preset_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_types
    ADD CONSTRAINT image_types_image_presets_image_preset_id_fk FOREIGN KEY (image_preset_id) REFERENCES public.image_presets(image_preset_id);


--
-- Name: task_categories task_categories_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_categories
    ADD CONSTRAINT task_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.task_categories(task_category_id);


--
-- Name: task_comments task_comments_employees_employee_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT task_comments_employees_employee_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id);


--
-- Name: task_comments task_comments_tasks_task_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_comments
    ADD CONSTRAINT task_comments_tasks_task_id_fk FOREIGN KEY (task_id) REFERENCES public.tasks(task_id);


--
-- Name: task_schedules task_schedules_employees_employee_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_schedules
    ADD CONSTRAINT task_schedules_employees_employee_id_fk FOREIGN KEY (assigned_employee_id) REFERENCES public.employees(employee_id);


--
-- Name: task_schedules task_schedules_task_categories_task_category_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_schedules
    ADD CONSTRAINT task_schedules_task_categories_task_category_id_fk FOREIGN KEY (task_category_id) REFERENCES public.task_categories(task_category_id);


--
-- Name: tasks tasks_employees_employee_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_employees_employee_id_fk FOREIGN KEY (assigned_employee_id) REFERENCES public.employees(employee_id);


--
-- Name: tasks tasks_task_categories_task_category_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_task_categories_task_category_id_fk FOREIGN KEY (task_category_id) REFERENCES public.task_categories(task_category_id);


--
-- Name: tasks tasks_task_schedules_task_schedule_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_task_schedules_task_schedule_id_fk FOREIGN KEY (task_schedule_id) REFERENCES public.task_schedules(task_schedule_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2z5d5x24fXACI4QPYB7YNbH0fGRO7focjLt2RrhcjMPwYJcbBsfe75aIduRvnFa

