--
-- PostgreSQL database dump
--

\restrict pLwlrbbePbUuVhIDlpoUWZzPGXDg17GZmuNtczXGaf14olCfbHVitrCJUoTbff3

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: email_message_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.email_message_type AS ENUM (
    'DELETE ACCOUNT CODE',
    'EMAIL UPDATE CODE',
    'SIGN-IN CODE',
    'WELCOME EMAIL'
);


--
-- Name: email_service; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.email_service AS ENUM (
    'MAILER_SEND'
);


--
-- Name: hawthorne_admin_session_token_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.hawthorne_admin_session_token_type AS ENUM (
    'SITE_PASSCODE',
    'EMPLOYEE_SITE_PASSCODE'
);


--
-- Name: text_message_service; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.text_message_service AS ENUM (
    'TWILIO'
);


--
-- Name: text_message_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.text_message_type AS ENUM (
    'PHONE NUMBER UPDATE CODE',
    'SIGN-IN CODE'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_generations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_generations (
    ai_generation_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    input_cost numeric(12,8) NOT NULL,
    output_cost numeric(12,8) NOT NULL,
    total_cost numeric(12,8) NOT NULL,
    ai_model_prompt_id bigint NOT NULL,
    input_tokens bigint NOT NULL,
    output_tokens bigint NOT NULL,
    item_type text NOT NULL,
    item_id bigint NOT NULL,
    raw_response jsonb NOT NULL
);


--
-- Name: ai_generations_ai_generation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_generations ALTER COLUMN ai_generation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_generations_ai_generation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: captured_exceptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.captured_exceptions (
    captured_exception_id bigint NOT NULL,
    site_id bigint NOT NULL,
    location text NOT NULL,
    exception_class text,
    exception_message text,
    note jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: captured_exceptions_captured_exception_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.captured_exceptions ALTER COLUMN captured_exception_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.captured_exceptions_captured_exception_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_sessions (
    employee_session_id bigint NOT NULL,
    employee_id bigint,
    hawthorne_admin_session_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token text,
    ip text,
    http_user_agent text,
    city text,
    region text,
    country text,
    success boolean DEFAULT false NOT NULL,
    signed_in_at timestamp with time zone,
    signed_out_at timestamp with time zone,
    invalid_passcode text,
    url text
);


--
-- Name: employee_sessions_employee_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_sessions ALTER COLUMN employee_session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_sessions_employee_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hawthorne_admin_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hawthorne_admin_sessions (
    hawthorne_admin_session_id bigint CONSTRAINT hawthorne_admin_site_sessio_hawthorne_admin_site_sessi_not_null NOT NULL,
    token text,
    ip text,
    http_user_agent text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT hawthorne_admin_site_sessions_created_at_not_null NOT NULL,
    city text,
    region text,
    country text,
    success boolean DEFAULT false NOT NULL,
    token_type public.hawthorne_admin_session_token_type,
    employee_id bigint,
    invalid_token_entered text,
    employee_signed_out boolean DEFAULT false NOT NULL
);


--
-- Name: hawthorne_admin_sessions_hawthorne_admin_session__seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hawthorne_admin_sessions ALTER COLUMN hawthorne_admin_session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hawthorne_admin_sessions_hawthorne_admin_session__seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sent_emails; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sent_emails (
    sent_email_id bigint NOT NULL,
    site_id bigint NOT NULL,
    user_id bigint,
    service public.email_service NOT NULL,
    message_type public.email_message_type CONSTRAINT sent_emails_email_type_not_null NOT NULL,
    service_template_id text NOT NULL,
    from_email text NOT NULL,
    to_email text NOT NULL,
    subject text NOT NULL,
    service_personalization jsonb,
    service_id text,
    exception_caught boolean NOT NULL,
    exception_type text,
    exception_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    service_sent boolean DEFAULT false NOT NULL,
    service_sent_at timestamp with time zone,
    service_delivered boolean DEFAULT false NOT NULL,
    service_delivered_at timestamp with time zone,
    service_soft_bounced boolean DEFAULT false NOT NULL,
    service_soft_bounced_at timestamp with time zone,
    service_hard_bounced boolean DEFAULT false NOT NULL,
    service_hard_bounced_at timestamp with time zone,
    service_opened boolean DEFAULT false NOT NULL,
    service_opened_at timestamp with time zone,
    service_clicked boolean DEFAULT false NOT NULL,
    service_clicked_at timestamp with time zone,
    service_unsubscribed boolean DEFAULT false NOT NULL,
    service_unsubscribed_at timestamp with time zone,
    service_spam_complaint boolean DEFAULT false NOT NULL,
    service_spam_complaint_at timestamp with time zone
);


--
-- Name: sent_emails_sent_email_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sent_emails ALTER COLUMN sent_email_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sent_emails_sent_email_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sent_text_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sent_text_messages (
    sent_text_message_id bigint NOT NULL,
    site_id bigint NOT NULL,
    user_id bigint,
    service public.text_message_service NOT NULL,
    message_type public.text_message_type NOT NULL,
    from_phone_number text NOT NULL,
    to_phone_number text NOT NULL,
    message text NOT NULL,
    service_id text,
    service_status text,
    exception_caught boolean NOT NULL,
    exception_type text,
    exception_code text,
    exception_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    service_queued_at timestamp with time zone,
    service_sending_at timestamp with time zone,
    service_sent_at timestamp with time zone,
    service_delivered_at timestamp with time zone,
    service_undelivered_at timestamp with time zone,
    service_failed_at timestamp with time zone,
    service_read_at timestamp with time zone
);


--
-- Name: sent_text_messages_sent_text_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sent_text_messages ALTER COLUMN sent_text_message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sent_text_messages_sent_text_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_actions (
    user_action_id bigint NOT NULL,
    site_id bigint NOT NULL,
    user_id bigint,
    action text NOT NULL,
    success boolean NOT NULL,
    failure_reason text,
    note jsonb,
    ip text,
    user_session_token text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_actions_user_action_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_actions ALTER COLUMN user_action_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_actions_user_action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    user_session_id bigint NOT NULL,
    token text NOT NULL,
    site_id bigint NOT NULL,
    user_id bigint,
    ip text,
    http_referer text,
    http_user_agent text,
    opening_url text,
    city text,
    region text,
    country text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    bot_checked boolean DEFAULT false NOT NULL,
    bot boolean DEFAULT false NOT NULL,
    browser_checked boolean DEFAULT false NOT NULL,
    browser_name text,
    browser_version text,
    platform text,
    device_type text,
    mobile boolean,
    browser_bot boolean DEFAULT false NOT NULL
);


--
-- Name: user_sessions_user_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_sessions ALTER COLUMN user_session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_user_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.versions (
    id bigint NOT NULL,
    item_type text NOT NULL,
    item_id bigint NOT NULL,
    event character varying NOT NULL,
    whodunnit character varying,
    object jsonb,
    object_changes jsonb,
    created_at timestamp with time zone,
    whodunnit_type character varying
);


--
-- Name: versions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: versions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.versions_id_seq OWNED BY public.versions.id;


--
-- Name: versions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versions ALTER COLUMN id SET DEFAULT nextval('public.versions_id_seq'::regclass);


--
-- Name: ai_generations ai_generations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_generations
    ADD CONSTRAINT ai_generations_pkey PRIMARY KEY (ai_generation_id);


--
-- Name: captured_exceptions captured_exceptions_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.captured_exceptions
    ADD CONSTRAINT captured_exceptions_pk PRIMARY KEY (captured_exception_id);


--
-- Name: employee_sessions employee_sessions_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_sessions
    ADD CONSTRAINT employee_sessions_pk PRIMARY KEY (employee_session_id);


--
-- Name: employee_sessions employee_sessions_uk_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_sessions
    ADD CONSTRAINT employee_sessions_uk_token UNIQUE (token);


--
-- Name: hawthorne_admin_sessions hawthorne_admin_sessions_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hawthorne_admin_sessions
    ADD CONSTRAINT hawthorne_admin_sessions_pk PRIMARY KEY (hawthorne_admin_session_id);


--
-- Name: hawthorne_admin_sessions hawthorne_admin_sessions_uk_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hawthorne_admin_sessions
    ADD CONSTRAINT hawthorne_admin_sessions_uk_token UNIQUE (token);


--
-- Name: sent_emails sent_emails_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sent_emails
    ADD CONSTRAINT sent_emails_pk PRIMARY KEY (sent_email_id);


--
-- Name: sent_emails sent_emails_uk_service_service_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sent_emails
    ADD CONSTRAINT sent_emails_uk_service_service_id UNIQUE (service, service_id);


--
-- Name: sent_text_messages sent_text_messages_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sent_text_messages
    ADD CONSTRAINT sent_text_messages_pk PRIMARY KEY (sent_text_message_id);


--
-- Name: sent_text_messages sent_text_messages_uk_service_service_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sent_text_messages
    ADD CONSTRAINT sent_text_messages_uk_service_service_id UNIQUE (service, service_id);


--
-- Name: user_actions user_actions_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_actions
    ADD CONSTRAINT user_actions_pk PRIMARY KEY (user_action_id);


--
-- Name: user_sessions user_sessions_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pk PRIMARY KEY (user_session_id);


--
-- Name: user_sessions user_sessions_uk_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_uk_token UNIQUE (token);


--
-- Name: versions versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versions
    ADD CONSTRAINT versions_pkey PRIMARY KEY (id);


--
-- Name: captured_exceptions_idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX captured_exceptions_idx_created_at ON public.captured_exceptions USING btree (created_at);


--
-- Name: captured_exceptions_idx_site_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX captured_exceptions_idx_site_id_created_at ON public.captured_exceptions USING btree (site_id, created_at);


--
-- Name: employee_sessions_idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX employee_sessions_idx_created_at ON public.employee_sessions USING btree (created_at);


--
-- Name: sent_emails_idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_created_at ON public.sent_emails USING btree (created_at);


--
-- Name: sent_emails_idx_hard_bounced; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_hard_bounced ON public.sent_emails USING btree (created_at) WHERE service_hard_bounced;


--
-- Name: sent_emails_idx_message_type_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_message_type_created_at ON public.sent_emails USING btree (message_type, created_at);


--
-- Name: sent_emails_idx_site_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_site_id_created_at ON public.sent_emails USING btree (site_id, created_at);


--
-- Name: sent_emails_idx_soft_bounced; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_soft_bounced ON public.sent_emails USING btree (created_at) WHERE service_soft_bounced;


--
-- Name: sent_emails_idx_spam_complaint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_spam_complaint ON public.sent_emails USING btree (created_at) WHERE service_spam_complaint;


--
-- Name: sent_emails_idx_to_email_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_to_email_trgm ON public.sent_emails USING gin (to_email public.gin_trgm_ops);


--
-- Name: sent_emails_idx_unsubscribed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_unsubscribed ON public.sent_emails USING btree (created_at) WHERE service_unsubscribed;


--
-- Name: sent_emails_idx_user_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_emails_idx_user_id_created_at ON public.sent_emails USING btree (user_id, created_at);


--
-- Name: sent_text_messages_idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_text_messages_idx_created_at ON public.sent_text_messages USING btree (created_at);


--
-- Name: sent_text_messages_idx_message_type_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_text_messages_idx_message_type_created_at ON public.sent_text_messages USING btree (message_type, created_at);


--
-- Name: sent_text_messages_idx_service_status_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_text_messages_idx_service_status_created_at ON public.sent_text_messages USING btree (service_status, created_at);


--
-- Name: sent_text_messages_idx_site_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_text_messages_idx_site_id_created_at ON public.sent_text_messages USING btree (site_id, created_at);


--
-- Name: sent_text_messages_idx_to_phone_number_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_text_messages_idx_to_phone_number_trgm ON public.sent_text_messages USING gin (to_phone_number public.gin_trgm_ops);


--
-- Name: sent_text_messages_idx_user_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sent_text_messages_idx_user_id_created_at ON public.sent_text_messages USING btree (user_id, created_at);


--
-- Name: user_actions_idx_action_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_action_created_at ON public.user_actions USING btree (action, created_at);


--
-- Name: user_actions_idx_admin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_admin ON public.user_actions USING btree (created_at) WHERE (ip = 'ADMIN'::text);


--
-- Name: user_actions_idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_created_at ON public.user_actions USING btree (created_at);


--
-- Name: user_actions_idx_failure_reason_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_failure_reason_trgm ON public.user_actions USING gin (failure_reason public.gin_trgm_ops);


--
-- Name: user_actions_idx_ip_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_ip_trgm ON public.user_actions USING gin (ip public.gin_trgm_ops);


--
-- Name: user_actions_idx_site_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_site_id_created_at ON public.user_actions USING btree (site_id, created_at);


--
-- Name: user_actions_idx_user_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_user_id_created_at ON public.user_actions USING btree (user_id, created_at);


--
-- Name: user_actions_idx_user_session_token_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_actions_idx_user_session_token_created_at ON public.user_actions USING btree (user_session_token, created_at);


--
-- Name: user_sessions_idx_city_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_city_trgm ON public.user_sessions USING gin (city public.gin_trgm_ops);


--
-- Name: user_sessions_idx_country_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_country_created_at ON public.user_sessions USING btree (country, created_at);


--
-- Name: user_sessions_idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_created_at ON public.user_sessions USING btree (created_at);


--
-- Name: user_sessions_idx_default_view; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_default_view ON public.user_sessions USING btree (created_at) WHERE ((NOT bot) AND bot_checked);


--
-- Name: user_sessions_idx_ip_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_ip_trgm ON public.user_sessions USING gin (ip public.gin_trgm_ops);


--
-- Name: user_sessions_idx_region_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_region_trgm ON public.user_sessions USING gin (region public.gin_trgm_ops);


--
-- Name: user_sessions_idx_site_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_site_id_created_at ON public.user_sessions USING btree (site_id, created_at);


--
-- Name: user_sessions_idx_user_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_sessions_idx_user_id_created_at ON public.user_sessions USING btree (user_id, created_at);


--
-- Name: versions_idx_item_type_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX versions_idx_item_type_created_at ON public.versions USING btree (item_type, created_at);


--
-- Name: versions_idx_item_type_item_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX versions_idx_item_type_item_id ON public.versions USING btree (item_type, item_id);


--
-- Name: versions_idx_whodunnit_type_whodunnit_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX versions_idx_whodunnit_type_whodunnit_created_at ON public.versions USING btree (whodunnit_type, whodunnit, created_at);


--
-- Name: employee_sessions employee_sessions_hawthorne_admin_sessions_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_sessions
    ADD CONSTRAINT employee_sessions_hawthorne_admin_sessions_fk FOREIGN KEY (hawthorne_admin_session_id) REFERENCES public.hawthorne_admin_sessions(hawthorne_admin_session_id);


--
-- PostgreSQL database dump complete
--

\unrestrict pLwlrbbePbUuVhIDlpoUWZzPGXDg17GZmuNtczXGaf14olCfbHVitrCJUoTbff3

